# Generated by Django 6.0.1 on 2026-02-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_customer_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('both', 'Buyer & Seller')], default='buyer', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='spouse_email',
            field=models.EmailField(blank=True, help_text="Spouse's email address", max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='spouse_first_name',
            field=models.CharField(blank=True, help_text="Spouse's first name", max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='spouse_last_name',
            field=models.CharField(blank=True, help_text="Spouse's last name", max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='spouse_phone',
            field=models.CharField(blank=True, help_text="Spouse's phone number", max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('potential', 'Potential Client'), ('active', 'Active Client'), ('closed', 'Closed Client'), ('lost', 'Lost Client'), ('inactive', 'Inactive Client')], default='potential', help_text='Current status of the client', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
