# Generated by Django 6.0.1 on 2026-02-03 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_client_note_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_notes', to='crm.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
