# Generated by Django 6.0.1 on 2026-02-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_add_lead_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='referral',
            field=models.CharField(blank=True, choices=[('office_lead', 'Office Lead'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('telephone', 'Telephone'), ('postcard', 'Postcard'), ('open_house', 'Open House'), ('other', 'Other')], max_length=20),
        ),
    ]
