# Generated by Django 6.0.1 on 2026-02-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_lead_note_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='referral',
            field=models.CharField(blank=True, choices=[('office_lead', 'Office Lead'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('telephone', 'Telephone'), ('postcard', 'Postcard'), ('open_house', 'Open House'), ('walk_in', 'Walk In'), ('website', 'Website'), ('email', 'Email'), ('phone', 'Phone'), ('text', 'Text'), ('other', 'Other')], max_length=20),
        ),
    ]
