# Generated by Django 6.0.1 on 2026-02-04 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_lead_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('under_contract', 'Under Contract'), ('closed', 'Closed'), ('canceled', 'Canceled')], default='active', max_length=20)),
                ('representation', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('dual', 'Dual Agent')], default='buyer', help_text='Your role in this transaction', max_length=10)),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Agreed commission %', max_digits=5, null=True)),
                ('file_number', models.CharField(blank=True, max_length=50)),
                ('lockbox_code', models.CharField(blank=True, max_length=50)),
                ('showing_instructions', models.TextField(blank=True)),
                ('listing_date', models.DateField(blank=True, help_text='Date property was listed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='crm.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('listing', 'Listing'), ('contract_agreement', 'Contract Agreement'), ('offer', 'Offer'), ('offer_expiration', 'Offer Expiration'), ('expiration_reminder', 'Expiration Reminder'), ('inspection', 'Inspection'), ('appraisal', 'Appraisal'), ('closing', 'Closing'), ('expiration', 'Expiration'), ('other', 'Other')], default='other', max_length=20)),
                ('label', models.CharField(blank=True, help_text="Override label (e.g. 'Final walk-through')", max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('is_critical', models.BooleanField(default=False, help_text='Show as deadline/reminder (e.g. offer expiration)')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='crm.transaction')),
            ],
            options={
                'ordering': ['order', 'date'],
            },
        ),
        migrations.CreateModel(
            name='TransactionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary_buyer', 'Primary Buyer'), ('primary_seller', 'Primary Seller'), ('buyers_agent', "Buyer's Agent"), ('sellers_agent', "Seller's Agent"), ('home_inspector', 'Home Inspector'), ('sellers_lawyer', "Seller's Lawyer"), ('buyers_lawyer', "Buyer's Lawyer"), ('lender', 'Lender'), ('title_company', 'Title Company'), ('other', 'Other')], max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('client', models.ForeignKey(blank=True, help_text='Link to existing client; leave blank for non-client (e.g. inspector).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_parties', to='crm.client')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='crm.transaction')),
            ],
            options={
                'verbose_name_plural': 'Transaction parties',
                'ordering': ['role', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='TransactionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.transaction')),
            ],
            options={
                'ordering': ['order', 'due_date', 'id'],
            },
        ),
    ]
