# Generated by Django 6.0.1 on 2026-02-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_transaction_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='final_sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final sales price (used for GCI when closed)', max_digits=12, null=True),
        ),
    ]
