# Generated by Django 6.0.1 on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_add_contact_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='RE CRM', max_length=100)),
                ('logo', models.FileField(blank=True, help_text='Logo image (e.g. PNG, SVG)', null=True, upload_to='app_admin/')),
                ('chart_colors', models.JSONField(blank=True, default=dict, help_text='Keys: primary, income_bar, sales_bar (hex colors)')),
            ],
            options={
                'verbose_name': 'Application settings',
                'verbose_name_plural': 'Application settings',
            },
        ),
        migrations.CreateModel(
            name='ChoiceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type', models.CharField(choices=[('client_type', 'Client type'), ('client_status', 'Client status'), ('lead_status', 'Lead status'), ('lead_referral', 'Lead referral source'), ('transaction_status', 'Transaction status'), ('transaction_representation', 'Transaction representation'), ('contact_type', 'Contact type')], db_index=True, max_length=30)),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name_plural': 'Choice lists',
                'ordering': ['list_type', 'order', 'label'],
            },
        ),
        migrations.AddConstraint(
            model_name='choicelist',
            constraint=models.UniqueConstraint(fields=('list_type', 'code'), name='crm_choicelist_unique_type_code'),
        ),
    ]
