# Generated by Django 6.0.1 on 2026-02-04

from django.db import migrations


def seed_choicelist(apps, schema_editor):
    ChoiceList = apps.get_model('crm', 'ChoiceList')
    AppSettings = apps.get_model('crm', 'AppSettings')

    # Ensure AppSettings row exists
    AppSettings.objects.get_or_create(pk=1, defaults={'app_name': 'RE CRM'})

    # Seed from model choices: (list_type, [(code, label, order), ...])
    data = [
        ('client_type', [('buyer', 'Buyer', 0), ('seller', 'Seller', 1), ('both', 'Buyer & Seller', 2)]),
        ('client_status', [
            ('potential', 'Potential Client', 0), ('active', 'Active Client', 1),
            ('closed', 'Closed Client', 2), ('lost', 'Lost Client', 3), ('inactive', 'Inactive Client', 4),
        ]),
        ('lead_status', [
            ('new', 'New', 0), ('attempted', 'Attempted to Contact', 1), ('in_progress', 'In Progress', 2),
            ('connected', 'Connected', 3), ('unqualified', 'Unqualified', 4), ('bad_timing', 'Bad Timing', 5),
        ]),
        ('lead_referral', [
            ('office_lead', 'Office Lead', 0), ('facebook', 'Facebook', 1), ('instagram', 'Instagram', 2),
            ('telephone', 'Telephone', 3), ('postcard', 'Postcard', 4), ('open_house', 'Open House', 5),
            ('walk_in', 'Walk In', 6), ('website', 'Website', 7), ('email', 'Email', 8),
            ('phone', 'Phone', 9), ('text', 'Text', 10), ('other', 'Other', 11),
        ]),
        ('transaction_status', [
            ('active', 'Active', 0), ('pending', 'Pending', 1), ('under_contract', 'Under Contract', 2),
            ('closed', 'Closed', 3), ('canceled', 'Canceled', 4),
        ]),
        ('transaction_representation', [('buyer', 'Buyer', 0), ('seller', 'Seller', 1), ('dual', 'Dual Agent', 2)]),
        ('contact_type', [
            ('vendor', 'Vendor', 0), ('lender', 'Lender', 1), ('agent', 'Agent', 2),
            ('title_company', 'Title Company', 3), ('inspector', 'Inspector', 4),
            ('attorney', 'Attorney', 5), ('other', 'Other', 6),
        ]),
    ]
    for list_type, items in data:
        for code, label, order in items:
            ChoiceList.objects.get_or_create(list_type=list_type, code=code, defaults={'label': label, 'order': order})


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_app_admin_models'),
    ]

    operations = [
        migrations.RunPython(seed_choicelist, noop),
    ]
