# Generated by Django 6.0.1 on 2026-02-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_appsettings_email_signature'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='choicelist',
            name='crm_choicelist_unique_type_code',
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='chart_colors',
            field=models.JSONField(blank=True, default=dict, help_text='Keys: buyer, seller, dual (hex colors for dashboard charts)'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='email_signature',
            field=models.TextField(blank=True, help_text='HTML signature appended to outgoing emails. Use &lt;a href="url"&gt; for links and &lt;img src="url"&gt; for images.'),
        ),
        migrations.AlterUniqueTogether(
            name='choicelist',
            unique_together={('list_type', 'code')},
        ),
    ]
