# Generated by Django (migration for inactivity timeout)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_user_profile_and_remove_app_settings_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='inactivity_timeout_minutes',
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text='App Admin only: log out after this many minutes of no mouse/keyboard activity. Set to 0 to disable.',
            ),
        ),
    ]
