# Generated by Django 6.0.1 on 2026-02-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_userprofile_mailchimp_constant_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='inactivity_timeout_minutes',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Log out after this many minutes of no mouse/keyboard activity (entire app). Set to 0 to disable.'),
        ),
    ]
