# Generated by Django 6.0.1 on 2026-02-11 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_alter_appsettings_inactivity_timeout_minutes'),
        ('crm', '0023_userprofile_constant_contact_list_id'),
    ]

    operations = [
    ]
